### ISSUE TITLE
Demonstrate a "cookie-get" event from a third-party on a specific page from search

### ISSUE THREAD

**Issue by mercator-working-group** [mercator-working-group/gemeente-social#3]
Javascript showing code execution on specific page from SERP. 
Demonstrate the technical evidence that shows how social widgets can leak information about your particular page visit on a specific page that may be concerning.

**Comment by iamliamc** [comment]
So I guess the angle I took was we don't really want to look at all the pages that are direct links out from gemeente landing pages, but start by looking at the gemeente pages themselves and the type of cookies actions they inact... I put my first stab and look around here... maybe you care about the linked out pages too let me know what you think is missing/could be improved/is worth extending here:
https://github.com/mercator-working-group/gemeente-social/blob/master/analysis/notebooks/cookie-discovery.ipynb

**Comment by mercator-working-group** [comment]
Nice notebook!
A couple nits that may make the analysis cleaner:
1- In cell 4 you can already drop columns you know you wont need so the
join is doing less work. [incognito', 'crawl_id', 'window_id', 'tab_id',
'extension_session_uuid'] are all very safe to throw out. Which will also
reduce the indeces generated.
2- The comments in cell 7 are great, it would be nice to get an additional
bit of insite into the total number of pages for which '19k javascript
events' are observed.
3- Intresting direction with the last cell, I think we can play around a
bit with the differences in behaviour if we use a stateful crawl that have
a facebook.com visit in it's history. It would be interesting to see what
specific information is being passed in the facebook interaction events.

If you are curious about the practices of some of the cookie setter parties
you can use this handy tool to dig in a bit: https://whotracks.me/trackers

**Comment by iamliamc** [comment]
1. Done
2. Thanks, I added some simple graphs to see the distribution of javascript events across our parent urls and also the javascript events across the script_urls (hopefully that was the direction you were thinking)
3. Hah yeah, I kinda dumped the analysis there to get picked back up. I've kind of started with the idea of parsing all the cookies in the 'value' field and creating a new dataframe with parent_url, script_url, javascript_cookie "Key" to see what the population of cookies themselves looks like... because clearly enough the _fbp is a facebook tracking pixel... 
4. Since much of the set relates to google analytics I think I need to do some research on it's functionality and see if there is a session level / cross domain / tracking functionality set or if it's really well contained on a single site analytics vibe (doubtful)
